version: '3.8'

services:
  flask-vulnerable-app:
    image: flask-vulnerable-app
    container_name: flask-vulnerable-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: always
